#! /bin/bash

## DevPod dotfile install
if [ ${DEVPOD} == "true" ]; then
	export XDG_CONFIG_HOME="${HOME}/.config"
	mkdir -p "${XDG_CONFIG_HOME}"
	sh -c "$(curl -fsLS get.chezmoi.io)" -- init https://github.com/tepene/dotfiles.git -- apply --force "${XDG_CONFIG_HOME}/nvim"
fi
